// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportFile(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ExportFile'](arg1, arg2);
}

export function Startup(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['Startup'](arg1, arg2);
}
