// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConfirmDialog(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ConfirmDialog'](arg1, arg2);
}

export function DeletePages(arg1) {
  return window['go']['avnacio']['IOManager']['DeletePages'](arg1);
}

export function DuplicatePages(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['DuplicatePages'](arg1, arg2);
}

export function ExportFile(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['ExportFile'](arg1, arg2);
}

export function ReadPages(arg1) {
  return window['go']['avnacio']['IOManager']['ReadPages'](arg1);
}

export function Startup(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['Startup'](arg1, arg2);
}

export function WritePages(arg1, arg2) {
  return window['go']['avnacio']['IOManager']['WritePages'](arg1, arg2);
}
