// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Download(arg1) {
  return window['go']['avnacserver']['UnsplashService']['Download'](arg1);
}

export function Photos(arg1, arg2) {
  return window['go']['avnacserver']['UnsplashService']['Photos'](arg1, arg2);
}

export function Search(arg1, arg2, arg3) {
  return window['go']['avnacserver']['UnsplashService']['Search'](arg1, arg2, arg3);
}
