// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {avnacserver} from '../models';

export function Download(arg1:string):Promise<void>;

export function Photos(arg1:number,arg2:number):Promise<avnacserver.UnsplashFeedResult>;

export function Search(arg1:string,arg2:number,arg3:number):Promise<avnacserver.UnsplashFeedResult>;
