// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKey(arg1:string):Promise<void>;

export function GetKey(arg1:string):Promise<string>;

export function SetKey(arg1:string,arg2:string):Promise<void>;
