// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKey(arg1) {
  return window['go']['avnacsecrets']['SecretsManager']['DeleteKey'](arg1);
}

export function GetKey(arg1) {
  return window['go']['avnacsecrets']['SecretsManager']['GetKey'](arg1);
}

export function SetKey(arg1, arg2) {
  return window['go']['avnacsecrets']['SecretsManager']['SetKey'](arg1, arg2);
}
