// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {avnacconfig} from '../models';

export function AddWatcher(arg1:any):Promise<void>;

export function Get():Promise<avnacconfig.AppConfig>;

export function Save(arg1:avnacconfig.AppConfig):Promise<void>;

export function Startup(arg1:string):Promise<void>;
