// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddWatcher(arg1) {
  return window['go']['avnacconfig']['ConfigManager']['AddWatcher'](arg1);
}

export function Get() {
  return window['go']['avnacconfig']['ConfigManager']['Get']();
}

export function Save(arg1) {
  return window['go']['avnacconfig']['ConfigManager']['Save'](arg1);
}

export function Startup(arg1) {
  return window['go']['avnacconfig']['ConfigManager']['Startup'](arg1);
}
