// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {assetserver} from '../models';

export function GetVersion():Promise<string>;

export function MediaProxyMiddleware():Promise<assetserver.Middleware>;
