// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {avnacconfig} from '../models';
import {assetserver} from '../models';

export function GetConfig():Promise<avnacconfig.AppConfig>;

export function MediaProxyMiddleware():Promise<assetserver.Middleware>;

export function SaveConfig(arg1:avnacconfig.AppConfig):Promise<void>;
